# Generated by Django 2.0 on 2018-01-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EazyHacks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HackOverview',
        ),
    ]
