# Generated by Django 2.0 on 2018-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EazyHacks', '0002_delete_hackoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackOverview',
            fields=[
                ('Hack_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
