# Generated by Django 2.0 on 2018-01-19 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EazyHacks', '0003_hackoverview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HackOverview',
        ),
    ]
