# Generated by Django 2.0 on 2018-01-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EazyHacks', '0005_auto_20180119_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackdetails',
            name='Hack_id',
        ),
        migrations.DeleteModel(
            name='HackDetails',
        ),
        migrations.DeleteModel(
            name='HackOverview',
        ),
    ]
